// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/module_include_list/module_include_list.go - DO NOT EDIT.

package include

import (
	// Import packages that need to register themselves.
	_ "github.com/elastic/beats/v7/x-pack/filebeat/input/gcppubsub"
	_ "github.com/elastic/beats/v7/x-pack/filebeat/module/gcp"
	_ "github.com/elastic/beats/v7/x-pack/filebeat/processors/add_nomad_metadata"
	_ "github.com/elastic/beats/v7/x-pack/filebeat/processors/decode_cef"
)
